steps:
  # Step 1: Enable required APIs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis'
    args:
      - services
      - enable
      - compute.googleapis.com
      - monitoring.googleapis.com
      - logging.googleapis.com
      - storage.googleapis.com

  # Step 2: Upload workload runner to Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-workload-runner'
    args:
      - cp
      - scripts/workload_runner.sh
      - gs://${_BUCKET}/startup_scripts/workload_runner.sh

  # Step 3: Provision VMs and run benchmarks
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'provision-and-run'
    entrypoint: 'bash'
    args:
      - ./scripts/provision_and_run.sh
    env:
      - 'BUCKET=${_BUCKET}'
      - 'PROJECT_ID=${PROJECT_ID}'


options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET: "placeholder-bucket-name"

# timeout 2 hours
timeout: 7200s
